# Generated by Django 4.0.6 on 2022-07-25 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=30)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=None)),
                ('bio', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'userAccount',
                'verbose_name_plural': 'userAccounts',
            },
        ),
    ]
