# Generated by Django 4.0.6 on 2022-07-26 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_useraccount_birth_date_useraccount_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='password',
        ),
    ]
