# Generated by Django 4.0.6 on 2022-11-05 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='media_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdatas', to='account.data'),
        ),
    ]
