# Generated by Django 4.0.6 on 2022-11-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_useraccount_media_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='media_type',
            field=models.IntegerField(choices=[(0, 'ProfilePicture'), (1, 'PostImage')]),
        ),
    ]
