# Generated by Django 4.0.6 on 2022-07-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_useraccount_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
