# Generated by Django 4.0.6 on 2022-08-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_useraccount_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='profile_picture',
            field=models.ImageField(default='account/media/pic.jpeg', upload_to='account/media'),
        ),
    ]
