# Generated by Django 4.0.6 on 2022-09-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_useraccount_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_following',
            field=models.BooleanField(default=False),
        ),
    ]
