# Generated by Django 4.0.6 on 2022-11-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_useraccount_media_id'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media_id',
            field=models.ManyToManyField(blank=True, related_name='postmedias', to='account.data'),
        ),
    ]
